apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  replicas: 3        # ← était 2, maintenant 3
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: miladif/netflix:latest
        ports:
        - containerPort: 80
